export default function Home() {
  return (
    <main>
      <h1>DoneTimeLogger</h1>
      <p>がんばる社会人のための活動時間記録アプリ</p>
      <section>
        <h2>新規ログの作成</h2>
        <fieldset>
          <legend>活動内容の選択</legend>
          <p>
            ボタンをクリックすると開始時刻が記録されます。記録内容はあとから編集可能です。
          </p>
          <ul>
            <li>
              <button>運動</button>
            </li>
            <li>
              <button>語学学習</button>
            </li>
            <li>
              <button>個人開発</button>
            </li>
            <li>
              <button>読書</button>
            </li>
          </ul>
        </fieldset>
        <button>終了</button>
      </section>
      <section>
        <h2>コミット</h2>
        <button>記録を確定する</button>
        <p>一度記録を確定すると編集できなくなります。</p>
        <table>
          <thead>
            <tr>
              <th>日付</th>
              <th>開始時刻</th>
              <th>終了時刻</th>
              <th>休憩時間</th>
              <th>活動時間</th>
              <th>内容</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>2024/08/13</td>
              <td>19:10</td>
              <td>20:10</td>
              <td>0分</td>
              <td>1時間</td>
              <td>運動</td>
            </tr>
            <tr>
              <td>2024/08/13</td>
              <td>20:10</td>
              <td>21:10</td>
              <td>30分</td>
              <td>30分</td>
              <td>語学学習</td>
            </tr>
            <tr>
              <td>2024/08/13</td>
              <td>21:10</td>
              <td>22:10</td>
              <td>30分</td>
              <td>1時間</td>
              <td>語学学習</td>
            </tr>
          </tbody>
        </table>
      </section>
      <section>
        <h2>マージ</h2>
        <section>
          <h3>日にちごと</h3>
          <p>過去30日分だけ表示されます。</p>
          <table>
            <caption>2024/8/13</caption>
            <tbody>
              <tr>
                <th>運動</th>
                <td>1時間</td>
              </tr>
              <tr>
                <th>語学学習</th>
                <td>1時間30分</td>
              </tr>
            </tbody>
          </table>
          <table>
            <caption>2024/8/12</caption>
            <tbody>
              <tr>
                <th>運動</th>
                <td>30分</td>
              </tr>
              <tr>
                <th>読書</th>
                <td>30分</td>
              </tr>
            </tbody>
          </table>
        </section>
        <section>
          <h3>月ごと</h3>
          <p>過去12ヶ月分だけ表示されます。</p>
          <table>
            <caption>2024/7</caption>
            <tbody>
              <tr>
                <th>運動</th>
                <td>10時間30分</td>
              </tr>
            </tbody>
          </table>
        </section>
        <section>
          <h3>年ごと</h3>
          <table>
            <caption>2024</caption>
            <tbody>
              <tr>
                <th>運動</th>
                <td>100時間30分</td>
              </tr>
            </tbody>
          </table>
        </section>
      </section>
      {/* ---- GitHub ---- */}
      <article>
        GitHubリポジトリ
      </article>
    </main>
  )
}
